language: ruby
before_script:  
  - sudo apt-get install aspell libaspell-dev aspell-en
  - gem install raspell
  - bundle config build.raspell --with-opt-dir=
rvm:
    - 1.8.7

notifications:
email:
  recipients:
    - pamela.ocampo@gmail.com
  on_success: change
  on_failure: always