language: ruby
before_script:
  - sudo apt-get install aspell libaspell-dev aspell-en aspell-de
  - which aspell
  - bundle config build.raspell --with-opt-dir= && bundle install
rvm:
    - 1.8.7

notifications:
email:
  recipients:
    - pamela.ocampo@gmail.com
  on_success: change
  on_failure: always