language: ruby
before_install:  
    - sudo apt-get install aspell libaspell-dev aspell-en
    - gem install raspell
    - bundle config build.raspell --with-opt-dir=
before_script:
    - mysql -u root < db/grant_expertiza.sql    
    - rake db:create:all
    - rake db:test:prepare    
rvm:
    - 1.8.7

notifications:
email:
  recipients:
    - pamela.ocampo@gmail.com
  on_success: change
  on_failure: always