language: ruby
rvm:
    - 1.8.7
branches:
  only:
    - master
    - production
before_install:
    - uname -a
    - lsb_release -a
    - sudo apt-get update
    - sudo apt-get install git-core curl
    - sudo apt-get install libaspell-dev openjdk-6-jdk gcc libxml2 libxml2-dev libxslt1-dev mysql-server mysql-client
    - sudo apt-get install libmysqlclient-dev
    - sudo apt-get install graphviz
    - gem install ruby-debug -- --with-ruby-include=$rvm_path/src/ruby-1.8.7-head/
    - gem install raspell -- --with-ruby-include=$rvm_path/src/ruby-1.8.7-head/
    - bundle config build.raspell --with-opt-dir=
before_script:
    - mysql -u root < db/grant_expertiza.sql
    - export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64 
    - bundle install
    - bundle exec rake db:migrate
    - bundle exec rake db:test:prepare
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
script:
    - export RAILS_ENV=test
    - "export DISPLAY=:99.0 && bundle exec cucumber"
    # - "export DISPLAY=:99.0 && bundle exec rspec spec/"
notifications:
    email:
      recipients:
        - pamela.ocampo@gmail.com
      on_success: change
      on_failure: change
