development:
  adapter: mysql
  database: pg_development
  username: root
  password: krunal
  host: localhost
  port: 3306

test:
  adapter: mysql
  database: pg_test
  username: root
  password: krunal
  host: localhost
  port: 3306

cucumber:
  adapter: mysql
  database: pg_test
  username: root
  password: krunal
  host: localhost
  port: 3306

production:
  adapter: mysql
  database: pg_production
  username: root
  password:
  host: localhost
  port: 3306